dist: xenial

language: python

python:
    - 3.7
    - 3.6

matrix:
    include:
        - python: 3.7
          env: TOXENV=lint

#before_install:
#    - sudo apt-get update -y
#

install:
    - pip install tox tox-travis
    - eval $(dbus-launch --sh-syntax)

script:
    - tox

notifications:
    email: false